language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
env: 
  - SECRET=SuperSecretTokenKeyXXX&*& DB_URL=postgres://tpysktxx:Q3JLGS8Jd8saRWFSP9OWjY7GjiSDtL-S@raja.db.elephantsql.com:5432/tpysktxx
before_script: npm run pretest
script: npm test
after_success: npm run coveralls